GO ?= go
BINARY ?= bin/quotacore
SBOM ?= dist/sbom.cdx.json
CONTRACT ?= api/openapi.yaml
OGEN_VERSION ?= v1.24.0
OGEN ?= go run github.com/ogen-go/ogen/cmd/ogen@$(OGEN_VERSION)

.PHONY: build binary test race vet lint check-docs license-check sbom ci \
        generate generate-check docs docs-check ogen-check

build:
	$(GO) build ./...

binary:
	CGO_ENABLED=0 $(GO) build -o $(BINARY) ./cmd/quotacore

test:
	$(GO) test ./...

# Separate from `test` because -race needs cgo, and a machine with no C compiler
# can still run every other gate. CI runs this, where gcc is present.
race:
	CGO_ENABLED=1 $(GO) test -race ./...

vet:
	$(GO) vet ./...

lint:
	@unformatted="$$(gofmt -l .)"; if [ -n "$$unformatted" ]; then printf 'gofmt is required on:\n%s\n' "$$unformatted"; exit 1; fi
	$(GO) vet ./...

# Regenerate both derived artefacts of api/openapi.yaml: ogen's types, and the HTML page at
# /docs. Both are committed, so this is the target a developer runs after editing the contract
# and the target CI runs to prove nothing is stale.
generate: ogen-check docs

# `ogen-check` is named for what it verifies rather than for what it does, because running a
# generator and checking its output are different jobs. It regenerates into a scratch directory and
# compares bytes.
#
# It deliberately does not ask git whether the working tree is clean. That was the first version of
# this target, and it was wrong in a way that only showed up when someone tried to use it: a check
# that consults the index cannot distinguish "the generated code is stale" from "the generated code
# is correct but not yet committed", so it fails for every developer who is in the middle of the
# normal workflow of editing the contract, running `make generate` and committing both. It can only
# ever pass in CI, which means the one place it is genuinely needed is the only place it works.
# Comparing the regenerated bytes against the files on disk asks the question the target is named
# after, and answers the same way in CI and on a laptop.
#
# The pinned version matters: a different ogen emits different code for the same contract, and a
# check that passed on the developer's version and failed on CI's would be noise.
OGEN_SCRATCH ?= .ogen-check
OGEN_FILES = oas_cfg_gen.go oas_defaults_gen.go oas_interfaces_gen.go oas_json_gen.go \
             oas_parameters_gen.go oas_schemas_gen.go oas_validators_gen.go

ogen-check:
	@rm -rf $(OGEN_SCRATCH)
	@mkdir -p $(OGEN_SCRATCH)/generated $(OGEN_SCRATCH)/committed
	@$(OGEN) --config api/.ogen/ogen.yml --package api --target $(OGEN_SCRATCH)/generated $(CONTRACT)
	@for f in $(OGEN_FILES); do cp "api/$$f" "$(OGEN_SCRATCH)/committed/"; done
	@if diff -r $(OGEN_SCRATCH)/committed $(OGEN_SCRATCH)/generated > /dev/null 2>&1; then \
		rm -rf $(OGEN_SCRATCH); \
	else \
		printf 'the generated ogen files differ from the contract; run `make generate` and commit the result\n' >&2; \
		diff -r -u $(OGEN_SCRATCH)/committed $(OGEN_SCRATCH)/generated 2>&1 | head -40 >&2; \
		rm -rf $(OGEN_SCRATCH); \
		exit 1; \
	fi

# Write the reference page. The file is a rendering of the contract, so it is committed: a build
# step that produced it would mean the artefact a reader downloads and the one CI checked are not
# the same bytes.
docs:
	$(GO) run ./tools/gendocs -in $(CONTRACT) -out api/docs.html

# Fail when the committed page is not what the contract would generate. This is the check that
# stops the reference from drifting: the failure names the command that fixes it.
docs-check:
	$(GO) run ./tools/gendocs -in $(CONTRACT) -out api/docs.html -check

# `generate-check` is the combination, and it is what `ci` runs: neither target can be satisfied
# by hand-editing a generated file, because both regenerate before they compare.
generate-check: ogen-check docs-check

check-docs:
	@if command -v pwsh >/dev/null 2>&1; then \
		pwsh -NoProfile -File tools/check-docs.ps1 -Strict; \
	elif command -v powershell >/dev/null 2>&1; then \
		powershell -NoProfile -File tools/check-docs.ps1 -Strict; \
	else \
		printf 'neither pwsh nor powershell was found, so the specification cannot be checked\n' >&2; exit 1; \
	fi

license-check: binary
	@if command -v pwsh >/dev/null 2>&1; then \
		pwsh -NoProfile -File tools/license-scan.ps1 -Binary $(BINARY); \
	elif command -v powershell >/dev/null 2>&1; then \
		powershell -NoProfile -File tools/license-scan.ps1 -Binary $(BINARY); \
	else \
		printf 'neither pwsh nor powershell was found, so no licence can be checked\n' >&2; exit 1; \
	fi

sbom: binary
	@if command -v pwsh >/dev/null 2>&1; then \
		pwsh -NoProfile -File tools/license-scan.ps1 -Binary $(BINARY) -SbomPath $(SBOM); \
	elif command -v powershell >/dev/null 2>&1; then \
		powershell -NoProfile -File tools/license-scan.ps1 -Binary $(BINARY) -SbomPath $(SBOM); \
	else \
		printf 'neither pwsh nor powershell was found, so no SBOM can be produced\n' >&2; exit 1; \
	fi

ci: check-docs generate-check lint test license-check
