// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/google/uuid"
)

// ApplyPlanParams is parameters of applyPlan operation.
type ApplyPlanParams struct {
	// A plan identifier. Either the UUID or the plan key; both address a plan.
	ID string
}

// ArchiveFeatureParams is parameters of archiveFeature operation.
type ArchiveFeatureParams struct {
	// The feature key, as in the catalogue.
	FeatureKey FeatureKey
}

// ArchivePlanParams is parameters of archivePlan operation.
type ArchivePlanParams struct {
	// A plan identifier. Either the UUID or the plan key; both address a plan.
	ID string
}

// BalanceParams is parameters of balance operation.
type BalanceParams struct {
	// Your identifier for the tenant. The customer never handles an internal `tenant_id`.
	TenantExternalID OptExternalId `json:",omitempty,omitzero"`
	// Restrict to one feature. On `GET /v1/balance` it is optional, and omitting it returns the tenant's
	// full set, which is bounded by the plan's entitlement count (NFR-T5).
	FeatureKey OptFeatureKey `json:",omitempty,omitzero"`
}

// ClearTenantOverrideParams is parameters of clearTenantOverride operation.
type ClearTenantOverrideParams struct {
	// A tenant identifier. Either the UUID or the `external_id`; both address a tenant.
	ID string
	// The feature key, as in the catalogue.
	FeatureKey FeatureKey
}

// ConsumeParams is parameters of consume operation.
type ConsumeParams struct {
	// One key per logical operation, reused across every attempt including retries. Derive it from your
	// own durable operation identifier where one exists.
	//
	// A repeat with a matching fingerprint replays the stored response. A repeat with a different
	// fingerprint is `409 idempotency_key_reuse` and changes nothing. The window is 24 hours from
	// application, per tenant, and is not configurable.
	//
	// The one case no server can protect against: a retry with a new key is a second operation and is
	// charged twice. No scheme detects that (FS-03).
	IdempotencyKey IdempotencyKey
}

// DeleteTenantParams is parameters of deleteTenant operation.
type DeleteTenantParams struct {
	// A tenant identifier. Either the UUID or the `external_id`; both address a tenant.
	ID string
}

// ForceRolloverParams is parameters of forceRollover operation.
type ForceRolloverParams struct {
	// A tenant identifier. Either the UUID or the `external_id`; both address a tenant.
	ID string
}

// GetFeatureParams is parameters of getFeature operation.
type GetFeatureParams struct {
	// The feature key, as in the catalogue.
	FeatureKey FeatureKey
}

// GetPlanParams is parameters of getPlan operation.
type GetPlanParams struct {
	// A plan identifier. Either the UUID or the plan key; both address a plan.
	ID string
}

// GetTenantParams is parameters of getTenant operation.
type GetTenantParams struct {
	// A tenant identifier. Either the UUID or the `external_id`; both address a tenant.
	ID string
}

// GrantTenantParams is parameters of grantTenant operation.
type GrantTenantParams struct {
	// A tenant identifier. Either the UUID or the `external_id`; both address a tenant.
	ID string
}

// ListAuditParams is parameters of listAudit operation.
type ListAuditParams struct {
	// Opaque and signed. A tampered cursor is `400 validation_failed`, never a silent full scan. Newest
	// first, always, with a stable tiebreaker so a cursor is never ambiguous.
	Cursor OptString `json:",omitempty,omitzero"`
	// Page size. An empty page returns an empty array, never `null`.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Your identifier for the tenant. The customer never handles an internal `tenant_id`.
	TenantExternalID OptExternalId `json:",omitempty,omitzero"`
	// Start of the time range, RFC 3339 with an explicit offset. Same format as responses.
	From OptTimestamp `json:",omitempty,omitzero"`
	// End of the time range, RFC 3339 with an explicit offset.
	To OptTimestamp `json:",omitempty,omitzero"`
}

// ListFeaturesParams is parameters of listFeatures operation.
type ListFeaturesParams struct {
	// Opaque and signed. A tampered cursor is `400 validation_failed`, never a silent full scan. Newest
	// first, always, with a stable tiebreaker so a cursor is never ambiguous.
	Cursor OptString `json:",omitempty,omitzero"`
	// Page size. An empty page returns an empty array, never `null`.
	Limit OptInt32 `json:",omitempty,omitzero"`
}

// ListKeysParams is parameters of listKeys operation.
type ListKeysParams struct {
	// Opaque and signed. A tampered cursor is `400 validation_failed`, never a silent full scan. Newest
	// first, always, with a stable tiebreaker so a cursor is never ambiguous.
	Cursor OptString `json:",omitempty,omitzero"`
	// Page size. An empty page returns an empty array, never `null`.
	Limit OptInt32 `json:",omitempty,omitzero"`
}

// ListPlansParams is parameters of listPlans operation.
type ListPlansParams struct {
	// Opaque and signed. A tampered cursor is `400 validation_failed`, never a silent full scan. Newest
	// first, always, with a stable tiebreaker so a cursor is never ambiguous.
	Cursor OptString `json:",omitempty,omitzero"`
	// Page size. An empty page returns an empty array, never `null`.
	Limit OptInt32 `json:",omitempty,omitzero"`
}

// ListTenantsParams is parameters of listTenants operation.
type ListTenantsParams struct {
	// Opaque and signed. A tampered cursor is `400 validation_failed`, never a silent full scan. Newest
	// first, always, with a stable tiebreaker so a cursor is never ambiguous.
	Cursor OptString `json:",omitempty,omitzero"`
	// Page size. An empty page returns an empty array, never `null`.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Restrict the tenant list to one plan.
	PlanKey OptPlanKey `json:",omitempty,omitzero"`
}

// ListUsageEventsParams is parameters of listUsageEvents operation.
type ListUsageEventsParams struct {
	// Opaque and signed. A tampered cursor is `400 validation_failed`, never a silent full scan. Newest
	// first, always, with a stable tiebreaker so a cursor is never ambiguous.
	Cursor OptString `json:",omitempty,omitzero"`
	// Page size. An empty page returns an empty array, never `null`.
	Limit OptInt32 `json:",omitempty,omitzero"`
	// Restrict to one feature. On `GET /v1/balance` it is optional, and omitting it returns the tenant's
	// full set, which is bounded by the plan's entitlement count (NFR-T5).
	FeatureKey OptFeatureKey `json:",omitempty,omitzero"`
	// One of the seven ledger event types. Any other value is `400 validation_failed`, never an empty
	// result: a filter that silently matches nothing is worse than one that says no.
	EventType OptEventType `json:",omitempty,omitzero"`
	// Who caused the event. Any other value is `400 validation_failed`.
	Source OptEventSource `json:",omitempty,omitzero"`
	// Filter the ledger to one logical operation, by the key the customer sent. This is how a disputed
	// charge is resolved: the recorded outcome shows whether it was applied once or twice (UC-16).
	IdempotencyKey OptIdempotencyKey `json:",omitempty,omitzero"`
	// Start of the time range, RFC 3339 with an explicit offset. Same format as responses.
	From OptTimestamp `json:",omitempty,omitzero"`
	// End of the time range, RFC 3339 with an explicit offset.
	To OptTimestamp `json:",omitempty,omitzero"`
	// A tenant identifier. Either the UUID or the `external_id`; both address a tenant.
	ID string
}

// PlanImpactParams is parameters of planImpact operation.
type PlanImpactParams struct {
	// A plan identifier. Either the UUID or the plan key; both address a plan.
	ID string
}

// RefundParams is parameters of refund operation.
type RefundParams struct {
	// One key per logical operation, reused across every attempt including retries. Derive it from your
	// own durable operation identifier where one exists.
	//
	// A repeat with a matching fingerprint replays the stored response. A repeat with a different
	// fingerprint is `409 idempotency_key_reuse` and changes nothing. The window is 24 hours from
	// application, per tenant, and is not configurable.
	//
	// The one case no server can protect against: a retry with a new key is a second operation and is
	// charged twice. No scheme detects that (FS-03).
	IdempotencyKey IdempotencyKey
}

// ResumeTenantParams is parameters of resumeTenant operation.
type ResumeTenantParams struct {
	// A tenant identifier. Either the UUID or the `external_id`; both address a tenant.
	ID string
}

// RevokeKeyParams is parameters of revokeKey operation.
type RevokeKeyParams struct {
	// A key identifier (the UUID, not the secret).
	ID uuid.UUID
}

// SetTenantBalanceParams is parameters of setTenantBalance operation.
type SetTenantBalanceParams struct {
	// A tenant identifier. Either the UUID or the `external_id`; both address a tenant.
	ID string
}

// SuspendTenantParams is parameters of suspendTenant operation.
type SuspendTenantParams struct {
	// A tenant identifier. Either the UUID or the `external_id`; both address a tenant.
	ID string
}

// UpdateFeatureParams is parameters of updateFeature operation.
type UpdateFeatureParams struct {
	// The feature key, as in the catalogue.
	FeatureKey FeatureKey
}

// UpdatePlanParams is parameters of updatePlan operation.
type UpdatePlanParams struct {
	// A plan identifier. Either the UUID or the plan key; both address a plan.
	ID string
}

// UpdateTenantParams is parameters of updateTenant operation.
type UpdateTenantParams struct {
	// A tenant identifier. Either the UUID or the `external_id`; both address a tenant.
	ID string
}

// UpsertTenantOverrideParams is parameters of upsertTenantOverride operation.
type UpsertTenantOverrideParams struct {
	// A tenant identifier. Either the UUID or the `external_id`; both address a tenant.
	ID string
}
