// Code generated by ogen, DO NOT EDIT.
package api

type ApplyPlanRes interface {
	applyPlanRes()
}

type ArchiveFeatureRes interface {
	archiveFeatureRes()
}

type ArchivePlanRes interface {
	archivePlanRes()
}

type BalanceRes interface {
	balanceRes()
}

type CheckRes interface {
	checkRes()
}

type ClearTenantOverrideRes interface {
	clearTenantOverrideRes()
}

type ConsumeRes interface {
	consumeRes()
}

type CreateFeatureRes interface {
	createFeatureRes()
}

type CreateKeyRes interface {
	createKeyRes()
}

type CreatePlanRes interface {
	createPlanRes()
}

type CreateTenantRes interface {
	createTenantRes()
}

type DeleteTenantRes interface {
	deleteTenantRes()
}

type ForceRolloverRes interface {
	forceRolloverRes()
}

type GetFeatureRes interface {
	getFeatureRes()
}

type GetPlanRes interface {
	getPlanRes()
}

type GetTenantRes interface {
	getTenantRes()
}

type GrantTenantRes interface {
	grantTenantRes()
}

type ListAuditRes interface {
	listAuditRes()
}

type ListFeaturesRes interface {
	listFeaturesRes()
}

type ListKeysRes interface {
	listKeysRes()
}

type ListPlansRes interface {
	listPlansRes()
}

type ListTenantsRes interface {
	listTenantsRes()
}

type ListUsageEventsRes interface {
	listUsageEventsRes()
}

type PlanImpactRes interface {
	planImpactRes()
}

type RefundRes interface {
	refundRes()
}

type ResumeTenantRes interface {
	resumeTenantRes()
}

type RevokeKeyRes interface {
	revokeKeyRes()
}

type SetTenantBalanceRes interface {
	setTenantBalanceRes()
}

type SuspendTenantRes interface {
	suspendTenantRes()
}

type UpdateFeatureRes interface {
	updateFeatureRes()
}

type UpdatePlanRes interface {
	updatePlanRes()
}

type UpdateTenantRes interface {
	updateTenantRes()
}

type UpsertTenantOverrideRes interface {
	upsertTenantOverrideRes()
}
