// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *FeatureCreate) setDefaults() {
	{
		val := string("")
		s.Description.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Override) setDefaults() {
	{
		val := OverrideApplyAt("immediate")
		s.ApplyAt = val
	}
}

// setDefaults set default value of fields.
func (s *OverrideClearRequest) setDefaults() {
	{
		val := OverrideApplyAt("immediate")
		s.ApplyAt = val
	}
}

// setDefaults set default value of fields.
func (s *PlanCreate) setDefaults() {
	{
		val := string("")
		s.Description.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TenantCreate) setDefaults() {
	{
		val := string("UTC")
		s.Timezone.SetTo(val)
	}
}
